apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-github-workflow
  labels:
    app: tf-github-workflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tf-github-workflow
  template:
    metadata:
      labels:
        app: tf-github-workflow
    spec:
      containers:
        - name: web
          image: DOCKER_IMAGE_PLACEHOLDER
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tf-github-workflow
  labels:
    app: tf-github-workflow
spec:
  type: LoadBalancer
  selector:
    app: tf-github-workflow
  ports:
    - port: 80
      targetPort: 80
