name: DockerBuild
on:  
  push:
    tags:
      - '*'
  workflow_despatch: 

jobs: 
  build_and_push: 
    runs-on: ubuntu-latest 

    steps: 
    - name: clone repo 
      uses: action/checkout@v2

    - name: Setup Docker build 
      uses: docker/setup-buildx-action@v2 

    - name: Build Docker Image
      run: docker build -t "${{ secrets.DOCKERHUB_USERNAME_LIAM }}/mynginx:${{ github.ref_name }}" .
      working-directory: docker_liam

    - name: Build Docker Image ( latest )
      run: docker build -t "${{ secrets.DOCKERHUB_USERNAME_LIAM }}/mynginx:latest" .
      working-directory: docker_liam

    - name: Log into Docker
      run: echo "${{ secrets.DOCKERHUB_TOKEN_LIAM}}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME_LIAM }}" --password-stdin

    - name: Push Image ( incremental )
      run: docker push "${{ secrets.DOCKERHUB_USERNAME_LIAM }}/mynginx:${{ github.ref_name }}"
      working-directory: docker_liam

    - name: Push Image ( latest )
      run: docker push "${{ secrets.DOCKERHUB_USERNAME_LIAM }}/mynginx:latest"
      working-directory: docker_liam
      