name: Deploy to EKS

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Change to your region

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.19.0' # Change to your preferred version

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name tfcluster --region us-east-1 # Change to your cluster name and region

    - name: Update image version in deployment manifest
      run: |
        sed -i 's|image: zohirul/myimage:.*|image: zohirul/myimage:${{ github.event.workflow_run.outputs.image_tag }}|' deployment.yml
      working-directory: .

    - name: Apply Kubernetes manifests
      run: kubectl apply -f deployment.yml
      working-directory: .