name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch tags
      run: git fetch --tags

    - name: Increment version
      id: increment_version
      run: |
        current_version=$(git describe --tags --abbrev=0)
        IFS='.' read -r major minor patch <<< "$current_version"
        next_version="$major.$minor.$((patch + 1))"
        echo "::set-output name=next_version::$next_version"

    - name: Build and tag Docker image
      run: |
        docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/myimage:${{ steps.increment_version.outputs.next_version }}" .
      working-directory: Docker 
  
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/myimage:${{ steps.increment_version.outputs.next_version }}"
      working-directory: Docker

